# Generated by Django 6.1 on 2026-09-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_imagenproducto_y_portada_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rc',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RC (Discogs)'),
        ),
    ]
